### ISSUE TITLE
can we somehow remove/replace level or change circular problems? (iojs)

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ws#3]
Ok, so correct me if I'm wrong.

`level` depends on `level-packager` which depends on `levelup` which devDepends on `level-ws` (`remove-write-stream` branch) which in turn devDepends on `level`.

So I have this scenario:

* clone `level-ws` and checkout `tweaks` branch
* npm install fails on iojs since `level@0.18.0` is used and that version does not work with iojs

Which obviously leads us to the situation where we should fix `level` so it works with iojs (in order to get `level-ws` to install properly).

This basically means updating `level` to use `leveldown@~1.0.0` and also update `level-packager` to use an updated `levelup` which devDepends on this module that we are trying to install.

It seems a bit circular to me. Am I missing something here?

/cc @rvagg

**Comment by rvagg** [comment]
it's a devDep for level here tho right? so it shouldn't be a problem for "normal" users, but yeah, i guess something needs to be changed to remove the circular nature, perhaps just use levelup and leveldown directly from here for devdeps

**Comment by ralphtheninja** [comment]
On the todo list :)

**Comment by ralphtheninja** [comment]
This is not an issue anymore since `levelup` no longer devDepends on `level-ws`
