### ISSUE TITLE
Test flushing of remaining buffer in _final

### ISSUE THREAD

**Issue by vweevers** [Level/level-ws#82]
https://github.com/Level/level-ws/blob/182314539e46f1b0c056a622c676612ad005b447/level-ws.js#L89-L92

Lines 90-91 are [not covered atm](https://coveralls.io/builds/17764743/source?filename=level-ws.js#L90).

**Comment by vweevers** [comment]
I need to write a cleaner test but I think there's another (new) race condition 😄

**Comment by ralphtheninja** [comment]
`level-race-condition-stream` :laughing:

**Comment by vweevers** [comment]
It's the `process.nextTick` in here that makes all subsequent state management hard. I wouldn't mind publishing a simpler `_writev`-based module after this (under Level).

**Comment by vweevers** [comment]
Nailed down the new race condition:

- Write first entry, flush is scheduled (setting `this._flushing` to true)
- Write second entry while flushing is in progress
- This will schedule another flush (again setting `this._flushing` to true)
- First flush completes and sets `this._flushing` to false
- If the stream is then ended, `_final` will see `this._flushing === false` and not wait.

**Comment by vweevers** [comment]
Couple of ways to solve this:

1. Don't allow concurrent flushes, either by:
   1a. Having a second flush wait
   1b. Skipping the second flush. Do `if(!_self.flushing)` instead of `if (self._buffer.length === 0)`.
2. Instead of a boolean, keep a counter of pending flushes
3. ?

**Comment by ralphtheninja** [comment]
At a quick glance number 2 sounds like the easiest and simplest way to fix this. I might be wrong though :)

**Comment by vweevers** [comment]
I opted for 1b (#92) but can do an alternative PR if you like
