### ISSUE TITLE
Change maxBufferLength logic

### ISSUE THREAD

**Issue by vweevers** [Level/level-ws#83]
https://github.com/Level/level-ws/blob/182314539e46f1b0c056a622c676612ad005b447/level-ws.js#L32-L35

Rather than ignoring writes, we can pause until the current buffer is flushed. Along the lines of:

```js
self.once('_flush', function (err) {
  if (err) return next(err)
  self._write(d, enc, next)
}) 
```

**Comment by ralphtheninja** [comment]
SGTM!

**Comment by vweevers** [comment]
Could there be a case where this throws?

```js
  if (self._options.maxBufferLength &&
      self._buffer.length > self._options.maxBufferLength) {
    if (!self._flushing) {
      throw new Error('prevent this')
    }
    
    self.once('_flush', function (err) {
      if (err) return next(err)
      self._write(data, enc, next)
    })
  }
```

**Comment by vweevers** [comment]
Yup! Race condition number three!

**Comment by vweevers** [comment]
@ralphtheninja WDYT about doing:

```js
WriteStream.prototype._write = function (data, enc, next) {
  var self = this
  if (self.destroyed) return

  if (!self._flushing) {
    self._flushing = true
    process.nextTick(function () { self._flush() })
  }

  self._buffer.push(extend({ type: self._options.type }, data))

  if (self._options.maxBufferLength &&
      self._buffer.length >= self._options.maxBufferLength) {
    self.once('_flush', next)
  } else {
    next()
  }
}
```

On every `_write` we push to the buffer and if there's too much buffered, we wait until it's flushed.

**Comment by ralphtheninja** [comment]
This sounds good because we lift out the `!self._flushing` from both if-statements.

**Comment by ralphtheninja** [comment]
I guess `highWaterMark` is handled by `Writable` and it decides when to call `_write()`?

**Comment by vweevers** [comment]
It's a soft limit. If the internal buffer of `Writable` is full, `ws.write(..)` will return false. People can choose to ignore that, and I guess originally, `maxBufferLength` was a measure against that (and a hard limit).

**Comment by vweevers** [comment]
Maybe we need both options. Where reaching `maxBufferLength` signals to `Writable` "stop, our next batch will be too big", and reaching `highWaterMark` signals to upstream "stop if you can, we can't flush it in time".
