### ISSUE TITLE
npm run coverage error

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ws#85]
![screenshot from 2018-06-29 23-11-34](https://user-images.githubusercontent.com/308049/42115064-d3cc5170-7bf1-11e8-9b33-0334fddaa6fa.png)

**Comment by vweevers** [comment]
It's not for local use. Perhaps we should move the command to `.travis.yml`?

**Comment by ralphtheninja** [comment]
> It's not for local use. Perhaps we should move the command to .travis.yml?

Aaah ok. Nah it's fine I think.
