### ISSUE TITLE
Pass through complete object in _write()

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ws#94]

**Comment by vweevers** [comment]
To what extent do you want to restore it?

**Comment by ralphtheninja** [comment]
To the state it was before I started removing it :)

**Comment by ralphtheninja** [comment]
Or do you think it's enough with the encodings in `_write()`?

**Comment by vweevers** [comment]
I think it's enough to pass through the complete object (without knowledge of encodings), only add `type` if not set. If we define defaults here, they override encoding options of the db (set by the user).

**Comment by ralphtheninja** [comment]
> If we define defaults here, they override encoding options of the db (set by the user).

That's a really good argument! So lets scrap this issue and create a new one for passing through the whole object and make it cleaner using e.g. `xtend()`

**Comment by ralphtheninja** [comment]
Or we just rename this issue, nevermind :smile:
