### ISSUE TITLE
Remove toString()?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-ws#97]
And if not, maybe we should change the name from `'LevelUP.WriteStream'` to something else? Needs test as well.

**Comment by vweevers** [comment]
I have no opinion on removing it, but +1 to renaming

**Comment by vweevers** [comment]
If we don't know why we should have `toString`, we can't know what the (format of) the name should be. 

Let's remove `toString`.

**Comment by vweevers** [comment]
84d67ddf7ca5d4b2e9e698c7fbd1c81880a728db
